/* Generated By:JavaCC: Do not edit this line. UQLParserConstants.java */
package javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface UQLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AND = 5;
  /** RegularExpression Id. */
  int OR = 6;
  /** RegularExpression Id. */
  int SN = 7;
  /** RegularExpression Id. */
  int SHA = 8;
  /** RegularExpression Id. */
  int ST = 9;
  /** RegularExpression Id. */
  int SL = 10;
  /** RegularExpression Id. */
  int TN = 11;
  /** RegularExpression Id. */
  int THA = 12;
  /** RegularExpression Id. */
  int TMA = 13;
  /** RegularExpression Id. */
  int TT = 14;
  /** RegularExpression Id. */
  int TL = 15;
  /** RegularExpression Id. */
  int E = 16;
  /** RegularExpression Id. */
  int TOI = 17;
  /** RegularExpression Id. */
  int PID = 18;
  /** RegularExpression Id. */
  int LPAREN = 19;
  /** RegularExpression Id. */
  int RPAREN = 20;
  /** RegularExpression Id. */
  int EQUALS = 21;
  /** RegularExpression Id. */
  int NOTEQUAL = 22;
  /** RegularExpression Id. */
  int CONTAINS = 23;
  /** RegularExpression Id. */
  int THEN = 24;
  /** RegularExpression Id. */
  int EOL = 25;
  /** RegularExpression Id. */
  int STRING = 26;
  /** RegularExpression Id. */
  int QUOTED_STRING = 27;
  /** RegularExpression Id. */
  int EMPTY_STRING = 28;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"and\"",
    "\"or\"",
    "<SN>",
    "\"sha\"",
    "\"st\"",
    "\"sl\"",
    "\"tn\"",
    "\"tha\"",
    "\"tma\"",
    "\"tt\"",
    "\"tl\"",
    "\"e\"",
    "\"toi\"",
    "\"pid\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\"!=\"",
    "\"contains\"",
    "\"then\"",
    "<EOL>",
    "<STRING>",
    "<QUOTED_STRING>",
    "<EMPTY_STRING>",
  };

}
